
image: maven:3.9.6-eclipse-temurin-17

stages:
  - init
  - build
  - docker-build

variables:
  NODE_VERSION: "18"  # Adjust based on your project requirements
  IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH/app
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
cache:
  paths:
    - node_modules/
    - .m2/repository/

before_script:
  - echo "Starting Build Pipeline"

# build_frontend:
#   stage: build
#   image: node:${NODE_VERSION}
#   script:
#     - echo "Installing frontend dependencies"
#     - npm install
#     - echo "Building Tailwind CSS"
#     - npx tailwindcss -i ./src/input.css -o ./src/output.css --minify
#     - echo "Building JavaScript"
#     - npm run build
#   artifacts:
#     paths:
#       - dist/ # Adjust if your frontend build outputs elsewhere
#     expire_in: 1 hour
init:
  stage: init
  script:
    - echo "Initializaing"
    - mvn --version
    - java --version
build:
  stage: build
  script:
    - echo "Building backend with Maven"
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target

docker-build:
  stage: docker-build
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building Docker Image"
    - docker-compose build app
    - docker tag scm2.0:latest $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$IMAGE_TAG

# build-docker-image:
#   stage: build
#   image: docker:24.0.5
  services:
    - docker:24.0.5-dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG