version: '3.8'

services:
  app:
    build:
      context: .
    image: scm2.0:latest
    container_name: scm2.0
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/scm2.0
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: scm2.0
    platform: linux/amd64 # Ensures compatibility with Apple M1/M2 chips
