apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
  labels:
    app: mysql
    component: database
type: Opaque
data:
  # base64 encoded values:
  # echo -n "root1234" | base64 → cm9vdDEyMzQ=
  # echo -n "scm2.0" | base64 → c2NtMi4w
  # echo -n "root" | base64 → cm9vdA==
  mysql-root-password: cm9vdDEyMzQ=
  mysql-database: c2NtMi4w
  mysql-username: cm9vdA==
