apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scm2
  template:
    metadata:
      labels:
        app: scm2
    spec:
      containers:
      - name: scm2
        image: registry.gitlab.com/demoproject5930807/scm2-0:8790224a
        # imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db:3306/scm2.0
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root1234
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
      imagePullSecrets:
      - name: gitlab-registry-secret    