apiVersion: v1
kind: Service
metadata:
  name: scm2-service
  namespace: default
  labels:
    app: scm2
    component: backend
spec:
  type: NodePort
  selector:
    app: scm2
  ports:
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 30007
      protocol: TCP